Check that GENOMECI_BASEDIR env is set up

diff --git a/bin/process-test b/bin/process-test
--- a/bin/process-test
+++ b/bin/process-test
@@ -1,2 +1,7 @@
 #!/bin/bash
+if test -z "$GENOMECI_BASEDIR"
+then
+    echo "ERROR: must set GENOMECI_BASEDIR" 1>&2
+    exit 1
+fi
 "$GENOMECI_BASEDIR"/bin/model-process-common $1 process
